### PR TITLE
WDP200103-8

### PR DESCRIPTION
**Pull request by m-kw**
https://projects.kodilla.com/browse/WDP200103-8

There was a big mess with color variables in settings.scss and style files of components - a lot of shades of one color, mixed hex and rgb codes.

I defined the most common colors variables, added detailed color variables for components that use colors for the moment of PR and added comments so that other devs could find variables for a component which they are working on.

@Varenthein

### CODE REVIEW

**Comment by Varenthein** [comment]
@PatrykBulaKodilla Review request.

**Comment by Varenthein** [comment]
@m-kw Please resolve conflicts

**Comment by m-kw** [comment]
@Varenthein just done. I see that I can merge now myself. Can I? Or should I re-request review?

**Comment by Varenthein** [comment]
> @Varenthein just done. I see that I can merge now myself. Can I? Or should I re-request review?

You can do it yoruself, but only if you are 100% sure that conflicts are properly resolved.

**Pull request merged**
